// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace message {

static const char* MessageTran_method_names[] = {
  "/message.MessageTran/QueryInfo",
};

std::unique_ptr< MessageTran::Stub> MessageTran::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MessageTran::Stub> stub(new MessageTran::Stub(channel));
  return stub;
}

MessageTran::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_QueryInfo_(MessageTran_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MessageTran::Stub::QueryInfo(::grpc::ClientContext* context, const ::message::in& request, ::message::out* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_QueryInfo_, context, request, response);
}

void MessageTran::Stub::experimental_async::QueryInfo(::grpc::ClientContext* context, const ::message::in* request, ::message::out* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_QueryInfo_, context, request, response, std::move(f));
}

void MessageTran::Stub::experimental_async::QueryInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::out* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_QueryInfo_, context, request, response, std::move(f));
}

void MessageTran::Stub::experimental_async::QueryInfo(::grpc::ClientContext* context, const ::message::in* request, ::message::out* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_QueryInfo_, context, request, response, reactor);
}

void MessageTran::Stub::experimental_async::QueryInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::message::out* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_QueryInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::out>* MessageTran::Stub::AsyncQueryInfoRaw(::grpc::ClientContext* context, const ::message::in& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::out>::Create(channel_.get(), cq, rpcmethod_QueryInfo_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::message::out>* MessageTran::Stub::PrepareAsyncQueryInfoRaw(::grpc::ClientContext* context, const ::message::in& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::message::out>::Create(channel_.get(), cq, rpcmethod_QueryInfo_, context, request, false);
}

MessageTran::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MessageTran_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MessageTran::Service, ::message::in, ::message::out>(
          [](MessageTran::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::message::in* req,
             ::message::out* resp) {
               return service->QueryInfo(ctx, req, resp);
             }, this)));
}

MessageTran::Service::~Service() {
}

::grpc::Status MessageTran::Service::QueryInfo(::grpc::ServerContext* context, const ::message::in* request, ::message::out* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message

